application: nitya-and-sriram
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: media/img

- url: /css
  static_dir: media/css

- url: /js
  static_dir: media/js

- url: /.*
  script: wedding.app

skip_files:
- ^(.*/)?.*\.psd

libraries:
- name: PIL
  version: latest
- name: django
  version: latest
