application: nitya-and-sriram
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
    
- url: /remote_api
  script: $APPENGINE/google/appengine/ext/remote_api/handler.py
  login: admin
      
- url: /img
  static_dir: media/img

- url: /css
  static_dir: media/css

- url: /js
  static_dir: media/js

- url: /fancybox
  static_dir: media/fancybox

- url: /.*
  script: djangoappengine/main/main.py

skip_files:
- ^(.*/)?.*\.psd

libraries:
- name: PIL
  version: latest
- name: django
  version: latest

builtins:
- remote_api: on
