application: nitya-and-sriram
version: 1
runtime: python
api_version: 1

handlers:
- url: (.*)/
  static_files: index.html
  upload: index.html

- url: /img
  static_dir: media/img

- url: /css
  static_dir: media/css

- url: /js
  static_dir: media/js

skip_files:
- ^(.*/)?.*\.psd
